### ISSUE TITLE
tried Debian and Win10 and no luck

### ISSUE THREAD

**Issue by Vendo232** [cs4alhaider/teams-status-bot#2]
here is the error msg from Windows

`PS C:\teams-status-bot> py teams-status-bot.py
C:\teams-status-bot\teams-status-bot.py:16: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome("./chromedriver")
Traceback (most recent call last):
  File "C:\teams-status-bot\teams-status-bot.py", line 16, in <module>
    driver = webdriver.Chrome("./chromedriver")
  File "C:\Users\###\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\###\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 90, in __init__
    self.service.start()
  File "C:\Users\###\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 74, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\###\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\###\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application
PS C:\teams-status-bot>`

here is error msg from Debian

`/teams-status-bot$ python3 teams-status-bot.py
/home/server/teams-status-bot/teams-status-bot.py:16: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome("./chromedriver")
Traceback (most recent call last):
  File "/home/server/teams-status-bot/teams-status-bot.py", line 16, in <module>
    driver = webdriver.Chrome("./chromedriver")
  File "/home/server/.local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/server/.local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 90, in __init__
    self.service.start()
  File "/home/server/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 74, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: './chromedriver' `

**Comment by cs4alhaider** [comment]
I don't use WidowsOS at all, you can debug ot and open a pull request if you like to share the fix

**Comment by viniciusgati** [comment]
@Vendo232 try this solution
https://stackoverflow.com/questions/41468101/python-selenium-windows-chrome-webdriver-giving-error
